# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'akuma.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AKUMA(object):
    def setupUi(self, AKUMA):
        AKUMA.setObjectName("AKUMA")
        AKUMA.resize(430, 333)
        self.mkakuma = QtWidgets.QPushButton(AKUMA)
        self.mkakuma.setGeometry(QtCore.QRect(60, 190, 121, 81))
        self.mkakuma.setObjectName("mkakuma")
        self.hpakuma = QtWidgets.QPushButton(AKUMA)
        self.hpakuma.setGeometry(QtCore.QRect(250, 190, 121, 81))
        self.hpakuma.setObjectName("hpakuma")
        self.akumalabel = QtWidgets.QLabel(AKUMA)
        self.akumalabel.setGeometry(QtCore.QRect(80, 40, 251, 71))
        self.akumalabel.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.akumalabel.setStyleSheet("font: 75 italic 14pt \"Times New Roman\";\n"
"color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 255);")
        self.akumalabel.setTextFormat(QtCore.Qt.RichText)
        self.akumalabel.setObjectName("akumalabel")

        self.retranslateUi(AKUMA)
        QtCore.QMetaObject.connectSlotsByName(AKUMA)

    def retranslateUi(self, AKUMA):
        _translate = QtCore.QCoreApplication.translate
        AKUMA.setWindowTitle(_translate("AKUMA", "Form"))
        self.mkakuma.setText(_translate("AKUMA", "5MK"))
        self.hpakuma.setText(_translate("AKUMA", "2HP"))
        self.akumalabel.setText(_translate("AKUMA", "Какой удар будем изучать?"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    AKUMA = QtWidgets.QWidget()
    ui = Ui_AKUMA()
    ui.setupUi(AKUMA)
    AKUMA.show()
    sys.exit(app.exec_())
