# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwin.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_GlavOkno(object):
    def setupUi(self, GlavOkno):
        GlavOkno.setObjectName("GlavOkno")
        GlavOkno.resize(362, 600)
        self.centralwidget = QtWidgets.QWidget(GlavOkno)
        self.centralwidget.setObjectName("centralwidget")
        self.Akuma = QtWidgets.QPushButton(self.centralwidget)
        self.Akuma.setGeometry(QtCore.QRect(10, 200, 131, 91))
        self.Akuma.setObjectName("Akuma")
        self.Kolin = QtWidgets.QPushButton(self.centralwidget)
        self.Kolin.setGeometry(QtCore.QRect(210, 200, 141, 91))
        self.Kolin.setObjectName("Kolin")
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(40, 30, 261, 71))
        self.textEdit.setObjectName("textEdit")
        GlavOkno.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(GlavOkno)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 362, 21))
        self.menubar.setObjectName("menubar")
        GlavOkno.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(GlavOkno)
        self.statusbar.setObjectName("statusbar")
        GlavOkno.setStatusBar(self.statusbar)

        self.retranslateUi(GlavOkno)
        QtCore.QMetaObject.connectSlotsByName(GlavOkno)

    def retranslateUi(self, GlavOkno):
        _translate = QtCore.QCoreApplication.translate
        GlavOkno.setWindowTitle(_translate("GlavOkno", "MainWindow"))
        self.Akuma.setText(_translate("GlavOkno", "Akuma"))
        self.Kolin.setText(_translate("GlavOkno", "Kolin"))
        self.textEdit.setHtml(_translate("GlavOkno", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Выберите персонажа</p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    GlavOkno = QtWidgets.QMainWindow()
    ui = Ui_GlavOkno()
    ui.setupUi(GlavOkno)
    GlavOkno.show()
    sys.exit(app.exec_())
